
features:
  time-endpoint-enabled=false

spring:
  jpa.hibernate.ddl-auto=update
  datasource.url=${JDBC_DATABASE_URL}
  datasource.username=${JDBC_USERNAME}
  datasource.password=${JDBC_PASSWORD}
  datasource.driver-class-name =com.mysql.cj.jdbc.Driver
  show-sql = true

jackson:
  serialization.indent-output=true

server:
  error.include-message=always
  port=${PORT:8080}


